export const GET_ALL_ASIENTOS_REQUEST = 'GET_ALL_ASIENTOS_REQUEST';
export const GET_ALL_ASIENTOS_SUCCESS = 'GET_ALL_ASIENTOS_SUCCESS';
export const GET_ALL_ASIENTOS_FAILURE = 'GET_ALL_ASIENTOS_FAILURE';

export const GET_ASIENTO_BY_ID_REQUEST = 'GET_ASIENTO_BY_ID_REQUEST';
export const GET_ASIENTO_BY_ID_SUCCESS = 'GET_ASIENTO_BY_ID_SUCCESS';
export const GET_ASIENTO_BY_ID_FAILURE = 'GET_ASIENTO_BY_ID_FAILURE';

export const FILTROS_REQUEST = 'FILTROS_REQUEST';
export const FILTROS_SUCCESS = 'FILTROS_SUCCESS';
export const FILTROS_FAILURE = 'FILTROS_FAILURE';
